In [2]:
cd /home/greenman225/Code/github/donkey_golf

/home/greenman225/Code/github/donkey_golf

In [3]:
import sqlite3
import pandas as pd
import logging
import oyaml

from donkey_golf import config

# create logger
logger = logging.getLogger(__name__)
logger.setLevel(logging.DEBUG)

# create console handler and set level to debug
ch = logging.StreamHandler()
ch.setLevel(logging.DEBUG)

# create formatter
formatter = logging.Formatter('%(asctime)s - %(name)s - %(levelname)s - %(message)s')

# add formatter to ch
ch.setFormatter(formatter)

# add ch to logger
logger.addHandler(ch)

# Bringing in config and SQL dict
conf = config.DGConfig()
yaml_sql_dict = oyaml.load(open(conf.yaml_sql_loc))

/home/greenman225/Code/virtual_envs/donkey_env/lib/python3.6/site-packages/flask_sqlalchemy/__init__.py:794: FSADeprecationWarning: SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and will be disabled by default in the future.  Set it to True or False to suppress this warning.
  'SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and '
/home/greenman225/Code/github/donkey_golf/donkey_golf/data_utils.py:27: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  yaml_sql_dict = oyaml.load(open(conf.yaml_sql_loc))
/home/greenman225/Code/virtual_envs/donkey_env/lib/python3.6/site-packages/ipykernel_launcher.py:27: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.

In [6]:
cd donkey_golf/

/home/greenman225/Code/github/donkey_golf/donkey_golf

In [7]:
import data_utils as du

/home/greenman225/Code/github/donkey_golf/donkey_golf/data_utils.py:27: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  yaml_sql_dict = oyaml.load(open(conf.yaml_sql_loc))

In [9]:
sql = yaml_sql_dict.get('aggregate_team_score')
df = du.run_sql(sql)

In [11]:
df['user_score'] = df['to_par'].str.replace('+','').str.replace('E','0')

In [13]:
df.loc[df['to_par'] == 'CUT', 'user_score'] = '999'

In [14]:
df

,id,username,pos,player,to_par,thru,r1,r2,r3,r4,total_strokes,tourney_id,user_score
0,4,poo,-,Justin Rose,CUT,CUT,75,73,--,--,148,401056527,999
1,4,poo,T6,Dustin Johnson,-6,F,68,70,--,--,138,401056527,-6
2,4,poo,T36,Rory McIlroy,E,F,73,71,--,--,144,401056527,0
3,4,poo,T57,Takumi Kanaya (a),+3,F,73,74,--,--,147,401056527,3
4,4,poo,T36,Si Woo Kim,E,F,72,72,--,--,144,401056527,0
5,4,poo,T29,Viktor Hovland (a),-1,F,72,71,--,--,143,401056527,-1
6,4,poo,-,Justin Rose,CUT,CUT,75,73,--,--,148,401056527,999
7,4,poo,T6,Dustin Johnson,-6,F,68,70,--,--,138,401056527,-6
8,4,poo,T36,Rory McIlroy,E,F,73,71,--,--,144,401056527,0
9,4,poo,T36,Si Woo Kim,E,F,72,72,--,--,144,401056527,0
10,4,poo,T29,Viktor Hovland (a),-1,F,72,71,--,--,143,401056527,-1
11,4,poo,-,Jose Maria Olazabal,CUT,CUT,78,79,--,--,157,401056527,999
12,5,mike,T1,Francesco Molinari,-7,F,70,67,--,--,137,401056527,-7
13,5,mike,T6,Xander Schauffele,-6,F,73,65,--,--,138,401056527,-6
14,5,mike,-,Paul Casey,CUT,CUT,81,73,--,--,154,401056527,999
15,5,mike,T57,Takumi Kanaya (a),+3,F,73,74,--,--,147,401056527,3
16,5,mike,T29,Viktor Hovland (a),-1,F,72,71,--,--,143,401056527,-1
17,5,mike,T50,Li Haotong,+2,F,72,74,--,--,146,401056527,2
18,6,jeff,-,Justin Rose,CUT,CUT,75,73,--,--,148,401056527,999
19,6,jeff,T6,Dustin Johnson,-6,F,68,70,--,--,138,401056527,-6
20,6,jeff,T36,Rory McIlroy,E,F,73,71,--,--,144,401056527,0
21,6,jeff,T36,Si Woo Kim,E,F,72,72,--,--,144,401056527,0
22,6,jeff,T23,Tommy Fleetwood,-2,F,71,71,--,--,142,401056527,-2
23,6,jeff,T1,Jason Day,-7,F,70,67,--,--,137,401056527,-7
24,7,tiger,T6,Dustin Johnson,-6,F,68,70,--,--,138,401056527,-6
25,7,tiger,T1,Brooks Koepka,-7,F,66,71,--,--,137,401056527,-7
26,7,tiger,T16,Bryson DeChambeau,-3,F,66,75,--,--,141,401056527,-3
27,7,tiger,T12,Phil Mickelson,-4,F,67,73,--,--,140,401056527,-4
28,7,tiger,T1,Adam Scott,-7,F,69,68,--,--,137,401056527,-7
29,7,tiger,T10,Ian Poulter,-5,F,68,71,--,--,139,401056527,-5
30,9,donk,T6,Dustin Johnson,-6,F,68,70,--,--,138,401056527,-6
31,9,donk,T1,Brooks Koepka,-7,F,66,71,--,--,137,401056527,-7
32,9,donk,T16,Bryson DeChambeau,-3,F,66,75,--,--,141,401056527,-3
33,9,donk,T12,Phil Mickelson,-4,F,67,73,--,--,140,401056527,-4
34,9,donk,T1,Adam Scott,-7,F,69,68,--,--,137,401056527,-7
35,9,donk,T10,Ian Poulter,-5,F,68,71,--,--,139,401056527,-5

In [18]:
sql = '''
SELECT * FROM leaderboard
WHERE to_par NOT IN ('CUT')
'''
df = du.run_sql(sql)

In [21]:
df = df.loc[df['to_par'].str.len() <= 3]

In [23]:
df = du.scrape_espn_leaderboard()

Index(['pos', 'unnamed:_1', 'player', 'to_par', 'today', 'thru', 'r1', 'r2',
       'r3', 'r4', 'tot'],
      dtype='object')

In [25]:
df = df['in_progress']

In [28]:
def add_donkey_game_score(df):
    '''
    Will add a column called donkey score that should 
    convert the to_par string to an integer
    '''
    df.loc[df['to_par'] == 'E', 'donkey_score'] = 0
    df.loc[df['to_par'].str[:-1] == '+', 'donkey_score'] = df['to_par'].str[1:]
    df.loc[df['to_par'].str[:-1] == '-', 'donkey_score'] = df['to_par']
    
    return df

In [39]:
df

,pos,player,to_par,thru,r1,r2,r3,r4,total_strokes,tourney_id,donkey_score
0,T1,Francesco Molinari,-7,F,70,67,--,--,137,401056527,-7
1,T1,Jason Day,-7,F,70,67,--,--,137,401056527,-7
2,T1,Brooks Koepka,-7,F,66,71,--,--,137,401056527,-7
3,T1,Adam Scott,-7,F,69,68,--,--,137,401056527,-7
4,T1,Louis Oosthuizen,-7,F,71,66,--,--,137,401056527,-7
5,T6,Dustin Johnson,-6,F,68,70,--,--,138,401056527,-6
6,T6,Justin Harding,-6,F,69,69,--,--,138,401056527,-6
7,T6,Xander Schauffele,-6,F,73,65,--,--,138,401056527,-6
8,T6,Tiger Woods,-6,F,70,68,--,--,138,401056527,-6
9,T10,Ian Poulter,-5,F,68,71,--,--,139,401056527,-5
10,T10,Jon Rahm,-5,F,69,70,--,--,139,401056527,-5
11,T12,Patton Kizzire,-4,F,70,70,--,--,140,401056527,-4
12,T12,Matt Kuchar,-4,F,71,69,--,--,140,401056527,-4
13,T12,Phil Mickelson,-4,F,67,73,--,--,140,401056527,-4
14,T12,Charles Howell III,-4,F,73,67,--,--,140,401056527,-4
15,T16,Kiradech Aphibarnrat,-3,F,69,72,--,--,141,401056527,-3
16,T16,Bryson DeChambeau,-3,F,66,75,--,--,141,401056527,-3
17,T16,Justin Thomas,-3,F,73,68,--,--,141,401056527,-3
18,T16,Corey Conners,-3,F,70,71,--,--,141,401056527,-3
19,T16,Tony Finau,-3,F,71,70,--,--,141,401056527,-3
20,T16,Gary Woodland,-3,F,70,71,--,--,141,401056527,-3
21,T16,Rickie Fowler,-3,F,70,71,--,--,141,401056527,-3
22,T23,Thorbjorn Olesen,-2,F,71,71,--,--,142,401056527,-2
23,T23,Kevin Kisner,-2,F,69,73,--,--,142,401056527,-2
24,T23,J.B. Holmes,-2,F,70,72,--,--,142,401056527,-2
25,T23,Lucas Bjerregaard,-2,F,70,72,--,--,142,401056527,-2
26,T23,Charley Hoffman,-2,F,71,71,--,--,142,401056527,-2
27,T23,Tommy Fleetwood,-2,F,71,71,--,--,142,401056527,-2
28,T29,Bernhard Langer,-1,F,71,72,--,--,143,401056527,-1
29,T29,Rafael Cabrera Bello,-1,F,73,70,--,--,143,401056527,-1
...,...,...,...,...,...,...,...,...,...,...,...
58,T57,Alexander Noren,+3,F,75,72,--,--,147,401056527,3
59,T57,Billy Horschel,+3,F,72,75,--,--,147,401056527,3
60,T57,Zach Johnson,+3,F,74,73,--,--,147,401056527,3
61,T57,Takumi Kanaya (a),+3,F,73,74,--,--,147,401056527,3
62,T57,Emiliano Grillo,+3,F,72,75,--,--,147,401056527,3
63,T57,Branden Grace,+3,F,72,75,--,--,147,401056527,3
64,T57,Eddie Pepperell,+3,F,74,73,--,--,147,401056527,3
65,The following players failed to make the cut a...,The following players failed to make the cut a...,The following players failed to make the cut a...,The following players failed to make the cut a...,The following players failed to make the cut a...,The following players failed to make the cut a...,The following players failed to make the cut a...,The following players failed to make the cut a...,The following players failed to make the cut a...,401056527,NaN
66,-,Danny Willett,CUT,CUT,75,73,--,--,148,401056527,NaN
67,-,Kevin O'Connell (a),CUT,CUT,77,71,--,--,148,401056527,NaN
68,-,Sandy Lyle,CUT,CUT,73,75,--,--,148,401056527,NaN
69,-,Stewart Cink,CUT,CUT,76,72,--,--,148,401056527,NaN
70,-,Mike Weir,CUT,CUT,72,76,--,--,148,401056527,NaN
71,-,Sergio Garcia,CUT,CUT,73,75,--,--,148,401056527,NaN
72,-,Justin Rose,CUT,CUT,75,73,--,--,148,401056527,NaN
73,-,Adam Long,CUT,CUT,75,74,--,--,149,401056527,NaN
74,-,Brandt Snedeker,CUT,CUT,75,74,--,--,149,401056527,NaN
75,-,Charl Schwartzel,CUT,CUT,77,72,--,--,149,401056527,NaN
76,-,Fred Couples,CUT,CUT,78,71,--,--,149,401056527,NaN
77,-,Shugo Imahira,CUT,CUT,76,74,--,--,150,401056527,NaN
78,-,Shane Lowry,CUT,CUT,78,73,--,--,151,401056527,NaN
79,-,Larry Mize,CUT,CUT,77,74,--,--,151,401056527,NaN
80,-,Jovan Rebula (a),CUT,CUT,73,79,--,--,152,401056527,NaN
81,-,Matt Wallace,CUT,CUT,75,77,--,--,152,401056527,NaN
82,-,Michael Kim,CUT,CUT,76,78,--,--,154,401056527,NaN
83,-,Paul Casey,CUT,CUT,81,73,--,--,154,401056527,NaN
84,-,Ian Woosnam,CUT,CUT,80,76,--,--,156,401056527,NaN
85,-,Vijay Singh,CUT,CUT,80,76,--,--,156,401056527,NaN
86,-,Jose Maria Olazabal,CUT,CUT,78,79,--,--,157,401056527,NaN
87,-,Angel Cabrera,CUT,CUT,82,75,--,--,157,401056527,NaN

In [54]:
conf = config.DGConfig()

class SQLPull():
    def __init__(self, dict_key):
        self.full_sql_dict = oyaml.load(open(config.DGConfig.yaml_sql_loc))
        self.sql_dict = self.full_sql_dict.get(dict_key)
    
        self.get_sql()
        
    def get_sql(self):
        self.sql = self.sql_dict
        
    def execute_sql(self, sql):
        '''
        Execute SQL and return results
        '''
        logger.info("Executing SQL")
        with sqlite3.connect(conf.db_location) as conn:
            return pd.read_sql_query(sql ,conn)
    
    def run(self):
        self.data = self.execute_sql(self.sql)

In [55]:
test = SQLPull('pull_available_players')

/home/greenman225/Code/virtual_envs/donkey_env/lib/python3.6/site-packages/ipykernel_launcher.py:5: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  """

In [56]:
test.run()

2019-04-12 08:41:17,291 - simple_example - INFO - Executing SQL

In [52]:
test.data

                 player  tee_time  current_rank  events_played
0   Kevin O'Connell (a)   8:52 AM           NaN            NaN
1     Takumi Kanaya (a)   9:14 AM           NaN            NaN
2    Viktor Hovland (a)  10:31 AM           NaN            NaN
3       Devon Bling (a)  11:37 AM           NaN            NaN
4      Alvaro Ortiz (a)  12:10 PM           NaN            NaN
5      Jovan Rebula (a)  12:43 PM           NaN            NaN
6           Justin Rose   1:49 PM           1.0           46.0
7        Dustin Johnson   1:38 PM           2.0           46.0
8          Rory McIlroy  11:15 AM           3.0           45.0
9         Brooks Koepka   2:00 PM           4.0           43.0
10        Justin Thomas   1:49 PM           5.0           47.0
11    Bryson DeChambeau   1:38 PM           6.0           56.0
12   Francesco Molinari   1:16 PM           7.0           47.0
13             Jon Rahm  11:04 AM           8.0           51.0
14        Rickie Fowler  11:15 AM           9.0           45.0
15    Xander Schauffele  10:53 AM          10.0           56.0
16           Paul Casey   2:00 PM          11.0           47.0
17          Tiger Woods  11:04 AM          12.0           25.0
18      Tommy Fleetwood  10:53 AM          13.0           57.0
19            Jason Day   1:38 PM          14.0           42.0
20           Tony Finau   9:58 AM          15.0           55.0
21          Matt Kuchar   1:05 PM          16.0           56.0
22         Bubba Watson   1:27 PM          17.0           46.0
23         Patrick Reed  10:31 AM          18.0           61.0
24     Louis Oosthuizen  10:42 AM          19.0           42.0
25        Marc Leishman  10:42 AM          20.0           52.0
26      Patrick Cantlay   1:27 PM          21.0           41.0
27       Phil Mickelson   1:49 PM          22.0           46.0
28         Webb Simpson  10:31 AM          23.0           50.0
29        Gary Woodland  10:53 AM          24.0           53.0
..                  ...       ...           ...            ...
57             Kevin Na  11:59 AM          54.0           50.0
58           Si Woo Kim   9:25 AM          55.0           58.0
59      Emiliano Grillo   9:36 AM          59.0           52.0
60       Keith Mitchell   8:41 AM          60.0           59.0
61      Charley Hoffman  10:42 AM          66.0           55.0
62           Aaron Wise   9:03 AM          67.0           51.0
63      Satoshi Kodaira   1:27 PM          68.0           63.0
64        Shugo Imahira  12:54 PM          77.0           55.0
65        Danny Willett   9:14 AM          78.0           47.0
66        Corey Conners   8:30 AM          84.0           63.0
67         Zach Johnson   1:05 PM          87.0           47.0
68         Stewart Cink  11:48 AM          96.0           49.0
69       Patton Kizzire  11:26 AM          97.0           56.0
70           Kevin Tway   8:41 AM          98.0           58.0
71         Jimmy Walker  11:48 AM         102.0           43.0
72     Charl Schwartzel   9:47 AM         104.0           51.0
73            Adam Long   8:30 AM         108.0           59.0
74        Andrew Landry   8:30 AM         128.0           56.0
75        Martin Kaymer  11:37 AM         190.0           52.0
76          Michael Kim  11:26 AM         330.0           54.0
77      Trevor Immelman  11:37 AM         461.0           27.0
78          Vijay Singh  12:43 PM         480.0           26.0
79      Bernhard Langer  12:10 PM         835.0            3.0
80         Fred Couples   9:25 AM        1330.0            3.0
81        Angel Cabrera   9:03 AM        1575.0           29.0
82            Mike Weir   8:52 AM        1765.0           27.0
83          Ian Woosnam   8:41 AM        2035.0            1.0
84           Sandy Lyle  11:26 AM        2035.0            3.0
85           Larry Mize  11:48 AM        2035.0            1.0
86  Jose Maria Olazabal  11:59 AM        2035.0           14.0

[87 rows x 4 columns]

In [31]:
test.sql_dict

'SELECT a.*, b.current_rank, b.events_played FROM pre_tourney a LEFT JOIN rankings b ON a.player=b.player ORDER BY current_rank'

In [20]:
test.full_sql_dict

AttributeError: 'SQLPull' object has no attribute 'full_sql_dict'

In [8]:
sql_dict = oyaml.load(open(config.DGConfig.yaml_sql_loc))

/home/greenman225/Code/virtual_envs/donkey_env/lib/python3.6/site-packages/ipykernel_launcher.py:1: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  """Entry point for launching an IPython kernel.

In [10]:
sql_dict.keys()

dict_keys(['pull_available_players', 'users_team'])

In [11]:
user = sql_dict.get('users_team')

In [12]:
user

{'select': 'SELECT * from teams a INNER JOIN leaderboard b ON a.golfer = b.player',
 'where': 'WHERE id = {}'}

In [13]:
where_clause = user['where']

In [14]:
where_clause

'WHERE id = {}'

In [16]:
where_clause.format('radiohead')

'WHERE id = radiohead'